spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT default
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 2
      - laleh: 1
      - Areya: 1
      - Bruce: 1

server:
  port: 8881
  endpoints:
    web:
      exposure:
        include: "*"

