spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT default
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 15
      - laleh: 25
      - Areya: 35
      - Bruce: 45

server:
  port: 8881
  endpoints:
    web:
      exposure:
        include: "*"

