spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT default
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 11
      - laleh: 22
      - Areya: 33
      - Bruce: 44

server:
  port: 8881
  endpoints:
    web:
      exposure:
        include: "*"

