spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT from Test Profile
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 10
      - laleh: 49
      - Areya: 18
      - Bruce: 55

server:
  port: 8887
  endpoints:
    web:
      exposure:
        include: "*"

