spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT from Test Profile
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 20
      - laleh: 18
      - Areya: 19
      - Bruce: 10

server:
  port: 8887
  endpoints:
    web:
      exposure:
        include: "*"

