spring:
  application:
  name: SpringCloudConfigurationServer


principal: Mr Bean from GIT default
classroom:
  teacher: Miss Davidson from GIT
  students:
    count: 4

    names: Atoosa, Bruce, Area, Laleh
    marks:
      - Atoosa: 1
      - laleh: 2
      - Areya: 3
      - Bruce: 4

server:
  port: 8881
  endpoints:
    web:
      exposure:
        include: "*"

